# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ac531e50e5a3646086bc9506306cc8dacc9c6a2b4266a3423dbbe0aa8c60827b52b9940a7e656902ea0018178835d6c147cbc8d7e366a75ddc741ff38d34b4f

test:
  secret_key_base: 844820d50f8fe5458c0c89a6a89697704c3b91c6eaf5ff69ad1260777cb285134487e021e184e34fd0c93ec54c064639d70537c905a7c9ed3aa69e6d080e4b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
